### ISSUE TITLE
Unable to reproduce results in the paper

### ISSUE THREAD

**Issue by jasperGT** [NUS-SNL/Gordon#2]
Thanks for sharing the source code of your interesting paper! I am interested in reproducing the results from your paper.
Here is the command I used for testing reddit.com:
$ ping reddit.com (identify 20ms rtt)
$ mm-delay 40
$ ./multi-lanch.sh reddit.com 15
The attached figure is plotted using $ gnuplot plot.plt --persist. The results have positive noise. 
Do you have any suggestions for the testing results?
Also, there seems no instruction for start.py and tcpClassify.py. Could you provide instructions for those files? 
I used $python3 tcpClassify.py path/to/windows.csv. The classified TCP variant is illinois_loss instead of cubic.
![graph](https://user-images.githubusercontent.com/81185053/112155165-45fb6c00-8ba2-11eb-919e-31577ff1c616.png)

**Comment by MischMetal** [comment]
hi jasperGT, can you please tell me which operating system and kernel version you're using? Our measurements were done on Linux, kernel version 4.15.

**Comment by jasperGT** [comment]
Hi MischMetal, thanks for your response!
The operating system is Ubuntu 16.04 and the kernel version is 4.15.0-129-generic.

**Comment by MischMetal** [comment]
Hi Jasper, can I confirm that your Linux `tcp_sack` option is off?

**Comment by jasperGT** [comment]
Hi MischMetal, tcp_sack is confrimed to be 0. I also checked the code to turn off tcp_sack which is available in multi-launch.sh. Is there any issue to use Gordon for networks like campus ethernet (e.g., due to any firewall issue)?

**Comment by MischMetal** [comment]
All our measurements were done from aws servers. However, I don't think the firewall should cause the kinds of errors you're experiencing. I have tried to reproduce your measurement from Ubuntu 18.04 with kernel 4.15.0-117-generic while sitting behind my university firewall, but I am getting the expected CUBIC graph. I will try again on Ubuntu 16.04 and get back to you. Thank you for bringing this issue to our attention!
